# Generated by Django 5.1 on 2024-09-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieOrAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_order', models.PositiveIntegerField()),
                ('title_th', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('seasons', models.PositiveIntegerField()),
                ('viewing_platform', models.CharField(max_length=255)),
            ],
        ),
    ]
